package com.rohidekar.callgraph;

import org.apache.bcel.Repository;
import org.apache.bcel.classfile.JavaClass;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;

/**
 * TODO: Insert description here. (generated by ssarnobat)
 */
class DeferredRelationships {
  private static Logger log = Logger.getLogger(DeferredRelationships.class);

  public static void handleDeferredRelationships(Relationships relationships) {
    for (DeferredParentContainment aDeferredParentContainment :
        relationships.getDeferredParentContainments()) {
      JavaClass parentClass =
          relationships.getClassDef(aDeferredParentContainment.getParentClassName());
      handleDeferredParentContainment(relationships, aDeferredParentContainment, parentClass);
    }
    for (DeferredChildContainment containment : relationships.getDeferredChildContainment()) {
      MyClassVisitor.addContainmentRelationship(
          containment.getParentClass(), containment.getClassQualifiedName(), relationships, false);
    }
    for (DeferredSuperMethod deferredSuperMethod :
        relationships.getDeferSuperMethodRelationships()) {
      handleDeferredSuperMethod(relationships, deferredSuperMethod);
    }
  }

  private static void handleDeferredSuperMethod(
      Relationships relationships, DeferredSuperMethod deferredSuperMethod) {
    MyInstruction parentInstruction = MyMethodVisitor.getInstruction(
        deferredSuperMethod.getparentClassOrInterface(),
        deferredSuperMethod.getunqualifiedMethodName(), relationships);
    if (parentInstruction == null) {
      log.debug("Parent instruction was not found");
    } else {
      if (log.isDebugEnabled()) {
        log.debug(parentInstruction.getMethodNameQualified() + " -> "
            + deferredSuperMethod.gettarget().getMethodNameQualified());
      }
      if (!relationships.methodCallExists(deferredSuperMethod.gettarget().getMethodNameQualified(),
          parentInstruction.getMethodNameQualified())) {
        relationships.addMethodCall(parentInstruction.getMethodNameQualified(),
            deferredSuperMethod.gettarget(),
            deferredSuperMethod.gettarget().getMethodNameQualified());
      }
    }
  }

  private static void handleDeferredParentContainment(Relationships relationships,
      DeferredParentContainment aDeferredParentContainment, JavaClass parentClass) {
    if (parentClass == null) {
      try {
        parentClass = Repository.lookupClass(aDeferredParentContainment.getParentClassName());
      } catch (ClassNotFoundException e) {
        if (!Ignorer.shouldIgnore(aDeferredParentContainment.getParentClassName())) {
          if (log.isEnabledFor(Level.WARN)) {
            log.warn(aDeferredParentContainment.getParentClassName());
          }
        }
      }
    }
    if (parentClass != null) {
      MyClassVisitor.addContainmentRelationship(parentClass,
          aDeferredParentContainment.getChildClass().getClassName(), relationships, false);
    }
  }
}
