package com.rohidekar.callgraph;

/**
 * TODO: Insert description here. (generated by ssarnobat)
 */
public class GraphNodeString extends GraphNode {
  String _string;

  public GraphNodeString(String iString) {
    super(iString);
    _string = iString;
    if (iString.equals("java.lang.Object")){
      throw new IllegalAccessError();
    }
  }

  @Override
  protected String printTreeNode() {
    return _string;
  }

  @Override
  public int getPackageDepth() {
    return 0;
  }

}
