package com.rohidekar.callgraph;

import org.apache.bcel.classfile.JavaClass;

/**
 * TODO: Insert description here. (generated by ssarnobat)
 */
public class Ignorer {

  public static boolean shouldIgnore(JavaClass iClass) {
    return shouldIgnore(iClass.getClassName());
  }

  public static boolean shouldIgnore(String classFullName) {
    for (String substringToIgnore : Main.substringsToIgnore) {
      if (classFullName.contains(substringToIgnore)) {
        return true;
      }
    }
    System.err.println(classFullName + " was not ignored");
    return false;
  }

}
